## mysql连接
spring:
  datasource:
    url: jdbc:mysql://8.130.110.108:16826/example?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 7447664226Shi!
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true
